#
# solis-inv-esphome.yaml -- Ginlong Solis INV Inverter ESPhome definition file
#
# ! This file only works with Solis 'INV' type inverters !
# ! This file only works with the Solis S3 WiFi stick (Gen 3, EMW3080 chip) !
#
# (C) 2023 Hajo Noerenberg
#
# Usage: https://docs.libretuya.ml/docs/projects/esphome/#build-upload
#
# http://www.noerenberg.de/
# https://github.com/hn/ginlong-solis
#
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3.0 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.txt>.
#

esphome:
  name: solis-inv
  friendly_name: Ginlong Solis Inverter
  name_add_mac_suffix: true

libretuya:
  board: generic-rtl8710bn-2mb-788k
  framework:
    version: latest

logger:
  hardware_uart: SERIAL2

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret wifi_ap_ssid
    password: !secret wifi_ap_password

captive_portal:

#time:
#  - platform: sntp
#    id: sntp_time
#    timezone: "CET-1CEST,M3.5.0,M10.5.0/3"
#    servers: "de.pool.ntp.org"

interval:
  - interval: 1s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - switch.turn_on: led_green_net
        else:
          - switch.turn_off: led_green_net
  - interval: 1s
    then:
      - switch.toggle: led_orange_com

uart:
  id: uart_0
  tx_pin: PA23
  rx_pin: PA18
  baud_rate: 9600

modbus:
  flow_control_pin: PA19
  send_wait_time: 200ms
  id: mod_bus_solis

modbus_controller:
  - id: solis
    address: 0x1
    modbus_id: mod_bus_solis
    command_throttle: 200ms
    setup_priority: -10
#    update_interval: 10s

button:
  - platform: factory_reset
    name: Restart with factory default settings
    id: reset_all

switch:
  - platform: gpio
    restore_mode: ALWAYS_OFF
    pin:
      number: PA12
      mode: output
    id: led_orange_com
  - platform: gpio
    restore_mode: ALWAYS_OFF
    pin:
      number: PA05
      mode: output
    id: led_green_net

binary_sensor:
  - platform: gpio
    pin:
      number: PA08
      inverted: true
    id: button_reset
    on_click:
      min_length: 5s
      max_length: 300s
      then:
        - button.press: reset_all
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Working status Normal
    register_type: read
    address: 3071 # = 3072 - 1
    bitmask: 0x0001
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Working status Initializing
    register_type: read
    address: 3071 # = 3072 - 1
    bitmask: 0x0002
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Working status Grid off
    device_class: problem
    register_type: read
    address: 3071 # = 3072 - 1
    bitmask: 0x0004
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Working status Fault to stop
    device_class: problem
    register_type: read
    address: 3071 # = 3072 - 1
    bitmask: 0x0008
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Working status Standby
    register_type: read
    address: 3071 # = 3072 - 1
    bitmask: 0x0010
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Working status Derating
    register_type: read
    address: 3071 # = 3072 - 1
    bitmask: 0x0020
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Working status Limitating
    register_type: read
    address: 3071 # = 3072 - 1
    bitmask: 0x0040
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Working status Grid surge
    device_class: problem
    register_type: read
    address: 3071 # = 3072 - 1
    bitmask: 0x0100
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Working status Fan fault
    device_class: problem
    register_type: read
    address: 3071 # = 3072 - 1
    bitmask: 0x0200

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Active Power
    device_class: power
    state_class: measurement
    unit_of_measurement: W
    register_type: read
    address: 3004 # = 3005 - 1
    value_type: U_DWORD
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Total DC output power
    device_class: power
    state_class: measurement
    unit_of_measurement: W
    register_type: read
    address: 3006 # = 3007 - 1
    value_type: U_DWORD
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Total energy
    device_class: energy
    state_class: total_increasing
    unit_of_measurement: kWh
    register_type: read
    address: 3008 # = 3009 - 1
    value_type: U_DWORD
    skip_updates: 10
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Energy this month
    device_class: energy
    state_class: total_increasing
    unit_of_measurement: kWh
    register_type: read
    address: 3010 # = 3011 - 1
    value_type: U_DWORD
    skip_updates: 10
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Energy last month
    device_class: energy
    state_class: total_increasing
    unit_of_measurement: kWh
    register_type: read
    address: 3012 # = 3013 - 1
    value_type: U_DWORD
    skip_updates: 10
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Energy today
    device_class: energy
    state_class: total_increasing
    unit_of_measurement: kWh
    register_type: read
    address: 3014 # = 3015 - 1
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    skip_updates: 10
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Energy last day
    device_class: energy
    state_class: total_increasing
    unit_of_measurement: kWh
    register_type: read
    address: 3015 # = 3016 - 1
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    skip_updates: 10
  - platform: modbus_controller
    modbus_controller_id: solis
    name: DC voltage 1
    device_class: voltage
    state_class: measurement
    unit_of_measurement: V
    register_type: read
    address: 3021 # = 3022 - 1
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: solis
    name: DC current 1
    device_class: current
    state_class: measurement
    unit_of_measurement: A
    register_type: read
    address: 3022 # = 3023 - 1
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Inverter temperature
    device_class: temperature
    state_class: measurement
    unit_of_measurement: C
    register_type: read
    address: 3041 # = 3042 - 1
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Grid frequency
    device_class: frequency
    state_class: measurement
    unit_of_measurement: Hz
    register_type: read
    address: 3042 # = 3043 - 1
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

text_sensor:
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Product model
    register_type: read
    address: 2999 # = 3000 - 1
    response_size: 2
    raw_encode: HEXBYTES
    entity_category: diagnostic
    icon: mdi:factory
    skip_updates: 10
  - platform: modbus_controller
    modbus_controller_id: solis
    name: DSP software version
    register_type: read
    address: 3000 # = 3001 - 1
    response_size: 2
    raw_encode: HEXBYTES
    entity_category: diagnostic
    icon: mdi:chip
    skip_updates: 10
  - platform: modbus_controller
    modbus_controller_id: solis
    name: LCD software version
    register_type: read
    address: 3001 # = 3002 - 1
    response_size: 2
    raw_encode: HEXBYTES
    entity_category: diagnostic
    icon: mdi:chip
    skip_updates: 10
  - platform: modbus_controller
    modbus_controller_id: solis
    name: Inverter SN
    register_type: read
    address: 3060 # = 3061 - 1
    register_count: 4
    raw_encode: HEXBYTES
    entity_category: diagnostic
    icon: mdi:numeric
    skip_updates: 10

